- name: "Does node exist"
  ignore_errors: yes
  community.libvirt.virt:
    name: "{{ hostvars[host].name }}"
    command: status
  register: node_exists

- name: "destroy node"
  community.libvirt.virt:
    name: "{{ hostvars[host].name }}"
    command: destroy
  when: node_exists['status'] is defined and node_exists['status'] == 'running'
